// src/components/DoesItLookTheSame.js

export const wordProblemTemplates = [
  { question: "What does 'Does it look the same?' mean?", options: ["Checking if two things look alike", "Counting things", "Measuring things", "Painting shapes"], answer: "Checking if two things look alike" },
  { question: "What is symmetry?", options: ["Balance in shape", "A type of drawing", "A kind of color", "A kind of game"], answer: "Balance in shape" },
  { question: "A figure can be folded into two equal halves. What does it show?", options: ["Line of symmetry", "Rotation", "Pattern", "Difference"], answer: "Line of symmetry" },
  { question: "When you turn a shape and it still looks the same, it has:", options: ["Rotational symmetry", "No symmetry", "Line symmetry", "Mirror reflection"], answer: "Rotational symmetry" },
  { question: "Which of these shows line symmetry?", options: ["Butterfly", "Stone", "Cloud", "Mountain"], answer: "Butterfly" },
  { question: "What is a mirror image?", options: ["An image that looks opposite", "A shadow", "A copy drawn below", "A photograph"], answer: "An image that looks opposite" },
  { question: "Which alphabet has one line of symmetry?", options: ["A", "P", "R", "F"], answer: "A" },
  { question: "Which letter looks the same in a mirror?", options: ["A", "B", "C", "D"], answer: "A" },
  { question: "When a figure is turned around a center point, it is called:", options: ["Rotation", "Reflection", "Translation", "Scaling"], answer: "Rotation" },
  { question: "Which object shows rotation?", options: ["Fan", "Cup", "Book", "Bag"], answer: "Fan" },
  { question: "A square has how many lines of symmetry?", options: ["4", "2", "1", "3"], answer: "4" },
  { question: "A rectangle has how many lines of symmetry?", options: ["2", "4", "1", "3"], answer: "2" },
  { question: "A circle has how many lines of symmetry?", options: ["Many", "2", "1", "None"], answer: "Many" },
  { question: "A triangle with all equal sides has how many lines of symmetry?", options: ["3", "2", "1", "4"], answer: "3" },
  { question: "Which of these shapes has no line of symmetry?", options: ["Scalene triangle", "Square", "Circle", "Rectangle"], answer: "Scalene triangle" },
  { question: "Which alphabet has no line of symmetry?", options: ["F", "A", "H", "M"], answer: "F" },
  { question: "The line that divides a figure into equal halves is called:", options: ["Line of symmetry", "Diagonal", "Side", "Edge"], answer: "Line of symmetry" },
  { question: "A star looks the same when turned around. What does it show?", options: ["Rotational symmetry", "No symmetry", "Asymmetry", "Mirror image"], answer: "Rotational symmetry" },
  { question: "Which of these objects shows symmetry?", options: ["Butterfly", "Leaf", "Human face", "All of these"], answer: "All of these" },
  { question: "Which of these letters has two lines of symmetry?", options: ["H", "O", "X", "All of these"], answer: "All of these" },
  { question: "When you fold a paper and both parts match, it means:", options: ["It has symmetry", "It is torn", "It is different", "It is colored"], answer: "It has symmetry" },
  { question: "Which shape looks same on turning half a round?", options: ["Circle", "Rectangle", "Square", "Star"], answer: "Circle" },
  { question: "A fan blade turning shows:", options: ["Rotation", "Reflection", "Shadow", "Folding"], answer: "Rotation" },
  { question: "Mirror image of the letter E looks like:", options: ["Backward E", "Normal E", "Upside down E", "Nothing"], answer: "Backward E" },
  { question: "Which object shows both line and rotational symmetry?", options: ["Square", "Triangle", "Parallelogram", "Trapezium"], answer: "Square" },
  { question: "When you flip a figure, you get:", options: ["Mirror image", "New color", "Bigger size", "Pattern"], answer: "Mirror image" },
  { question: "If two figures are the same in size and shape, they are:", options: ["Identical", "Similar", "Different", "Mirror image"], answer: "Identical" },
  { question: "If a figure has the same shape but different size, it is:", options: ["Similar", "Identical", "Opposite", "Unequal"], answer: "Similar" },
  { question: "Which shape looks the same when turned one-fourth round?", options: ["Square", "Triangle", "Rectangle", "Oval"], answer: "Square" },
  { question: "If you fold a rectangle along its length, both parts match. What is it called?", options: ["Line of symmetry", "Rotation", "Corner", "Edge"], answer: "Line of symmetry" },
  { question: "A clock’s hands turning show:", options: ["Rotation", "Reflection", "Shadow", "Symmetry"], answer: "Rotation" },
  { question: "The letter X has how many lines of symmetry?", options: ["2", "1", "4", "None"], answer: "2" },
  { question: "Which of these shapes is symmetrical?", options: ["Heart shape", "Butterfly", "Leaf", "All of these"], answer: "All of these" },
  { question: "When you draw a shape and fold it perfectly, what do you see?", options: ["Two equal halves", "Different halves", "A new shape", "A broken line"], answer: "Two equal halves" },
  { question: "A rectangle looks the same when turned half round. True or False?", options: ["True", "False", "Sometimes", "Never"], answer: "True" },
  { question: "A circle looks the same in every direction. True or False?", options: ["True", "False", "Only at 90°", "Only at 180°"], answer: "True" },
  { question: "Which of these shapes is NOT symmetrical?", options: ["Scalene triangle", "Square", "Circle", "Rectangle"], answer: "Scalene triangle" },
  { question: "A square looks the same after how much turn?", options: ["1/4 turn", "1/2 turn", "Full turn", "All of these"], answer: "All of these" },
  { question: "Which figure has more than one line of symmetry?", options: ["Circle", "Square", "Rectangle", "All of these"], answer: "All of these" },
  { question: "A kite has how many lines of symmetry?", options: ["1", "2", "3", "4"], answer: "1" },
  { question: "Which letter looks same on turning upside down?", options: ["H", "O", "X", "All of these"], answer: "All of these" },
  { question: "The line dividing a butterfly into two equal wings is:", options: ["Line of symmetry", "Wing line", "Diagonal", "Edge"], answer: "Line of symmetry" },
  { question: "The line of symmetry is always a:", options: ["Straight line", "Curved line", "Zigzag line", "Broken line"], answer: "Straight line" },
  { question: "Which shape shows both line and rotation symmetry?", options: ["Circle", "Square", "Both A and B", "None"], answer: "Both A and B" },
  { question: "The mirror image of 2 looks like:", options: ["Backward 2", "Same 2", "Upside 2", "Different number"], answer: "Backward 2" },
  { question: "Which of these is not a symmetrical shape?", options: ["Letter F", "Letter A", "Letter O", "Letter M"], answer: "Letter F" },
  { question: "Which of these shows rotational symmetry in real life?", options: ["Ceiling fan", "Windmill", "Flower", "All of these"], answer: "All of these" },
  { question: "A human face shows:", options: ["Line symmetry", "Rotation", "Translation", "No symmetry"], answer: "Line symmetry" },
  { question: "If you place a mirror on the line of symmetry, what will you see?", options: ["A complete picture", "Half picture", "No picture", "Blurred picture"], answer: "A complete picture" },
  { question: "The mirror image of the word MOM looks:", options: ["Same as MOM", "Different", "Upside down", "Blank"], answer: "Same as MOM" },
  { question: "When both halves of an object are equal and same, it is:", options: ["Symmetrical", "Asymmetrical", "Odd", "Irregular"], answer: "Symmetrical" }
];
